-- Shared inventory filter snippet for smart_final_data (reference — copy into RPCs).
-- Table alias: f
--
-- Parameters: p_types, p_makes, p_models, p_locations, p_years, p_condition
--
--   AND (COALESCE(array_length(p_types, 1), 0) = 0 OR f.inv_type = ANY(p_types))
--   AND (COALESCE(array_length(p_makes, 1), 0) = 0 OR f.inv_make = ANY(p_makes))
--   AND (COALESCE(array_length(p_models, 1), 0) = 0 OR f.inv_model = ANY(p_models))
--   AND (
--     COALESCE(array_length(p_locations, 1), 0) = 0
--     OR TRIM(f.inv_location) = ANY(SELECT TRIM(loc) FROM unnest(p_locations) AS loc)
--   )
--   AND (
--     COALESCE(array_length(p_years, 1), 0) = 0
--     OR (f.inv_year ~ '^\d{4}$' AND f.inv_year::int = ANY(p_years))
--   )
--   AND (
--     UPPER(COALESCE(p_condition, 'BOTH')) = 'BOTH'
--     OR UPPER(f.inv_condition) = UPPER(p_condition)
--   )
