-- Master dealer locations (customer_id + location_name only).
-- Used by get_dealer_location_breakdown. Independent from inv_type / custom type.
-- Run smart_dealer_locations_simplify.sql if upgrading from the old multi-column table.

CREATE TABLE IF NOT EXISTS public.smart_dealer_locations (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  customer_id text NOT NULL,
  location_name text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT smart_dealer_locations_pkey PRIMARY KEY (id),
  CONSTRAINT smart_dealer_locations_customer_name_unique UNIQUE (customer_id, location_name)
);

CREATE INDEX IF NOT EXISTS idx_dealer_locations_customer
  ON public.smart_dealer_locations (customer_id);

COMMENT ON TABLE public.smart_dealer_locations IS
  'Configured store locations per dealer. Location donut uses this table.';

GRANT SELECT ON public.smart_dealer_locations TO anon, authenticated, service_role;
GRANT ALL ON public.smart_dealer_locations TO service_role;
