-- Simplify smart_dealer_locations → customer_id + location_name only.
-- Used by Location Breakdown donut (get_dealer_location_breakdown).
-- Run in Supabase SQL editor. Safe to re-run.
--
-- Important: ADD customer_id BEFORE copying from legacy client_id
-- (old table has client_id, not customer_id).

-- Fresh install only (no-op if table already exists with old columns).
CREATE TABLE IF NOT EXISTS public.smart_dealer_locations (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  customer_id text NOT NULL,
  location_name text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT smart_dealer_locations_pkey PRIMARY KEY (id)
);

-- 1) Add new columns first (nullable during migrate).
ALTER TABLE public.smart_dealer_locations
  ADD COLUMN IF NOT EXISTS customer_id text;

ALTER TABLE public.smart_dealer_locations
  ADD COLUMN IF NOT EXISTS location_name text;

ALTER TABLE public.smart_dealer_locations
  ADD COLUMN IF NOT EXISTS created_at timestamptz DEFAULT now();

ALTER TABLE public.smart_dealer_locations
  ADD COLUMN IF NOT EXISTS updated_at timestamptz DEFAULT now();

-- 2) Copy from legacy client_id → customer_id (only if client_id still exists).
DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public'
      AND table_name = 'smart_dealer_locations'
      AND column_name = 'client_id'
  ) THEN
    EXECUTE $sql$
      UPDATE public.smart_dealer_locations
      SET customer_id = TRIM(client_id)
      WHERE (customer_id IS NULL OR TRIM(customer_id) = '')
        AND client_id IS NOT NULL
        AND TRIM(client_id) <> ''
    $sql$;
  END IF;
END $$;

-- 3) If location_name empty but inv_match_value exists, copy that.
DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public'
      AND table_name = 'smart_dealer_locations'
      AND column_name = 'inv_match_value'
  ) THEN
    EXECUTE $sql$
      UPDATE public.smart_dealer_locations
      SET location_name = TRIM(inv_match_value)
      WHERE (location_name IS NULL OR TRIM(location_name) = '')
        AND inv_match_value IS NOT NULL
        AND TRIM(inv_match_value) <> ''
    $sql$;
  END IF;
END $$;

-- 4) Drop rows that still cannot map (no customer / no name) — empty junk only.
DELETE FROM public.smart_dealer_locations
WHERE customer_id IS NULL
   OR TRIM(customer_id) = ''
   OR location_name IS NULL
   OR TRIM(location_name) = '';

-- 5) Drop legacy constraints / columns.
ALTER TABLE public.smart_dealer_locations
  DROP CONSTRAINT IF EXISTS smart_dealer_locations_client_match_unique;

ALTER TABLE public.smart_dealer_locations
  DROP COLUMN IF EXISTS client_id,
  DROP COLUMN IF EXISTS dealer_name,
  DROP COLUMN IF EXISTS location_number,
  DROP COLUMN IF EXISTS inv_match_value,
  DROP COLUMN IF EXISTS page_match_value,
  DROP COLUMN IF EXISTS sort_order,
  DROP COLUMN IF EXISTS is_active;

-- 6) Enforce NOT NULL on the two kept columns.
ALTER TABLE public.smart_dealer_locations
  ALTER COLUMN customer_id SET NOT NULL;

ALTER TABLE public.smart_dealer_locations
  ALTER COLUMN location_name SET NOT NULL;

ALTER TABLE public.smart_dealer_locations
  ALTER COLUMN created_at SET DEFAULT now();

ALTER TABLE public.smart_dealer_locations
  ALTER COLUMN updated_at SET DEFAULT now();

UPDATE public.smart_dealer_locations
SET created_at = COALESCE(created_at, now()),
    updated_at = COALESCE(updated_at, now());

ALTER TABLE public.smart_dealer_locations
  ALTER COLUMN created_at SET NOT NULL;

ALTER TABLE public.smart_dealer_locations
  ALTER COLUMN updated_at SET NOT NULL;

-- 7) Dedupe then unique (customer_id, location_name).
DELETE FROM public.smart_dealer_locations a
USING public.smart_dealer_locations b
WHERE a.id > b.id
  AND TRIM(a.customer_id) = TRIM(b.customer_id)
  AND TRIM(a.location_name) = TRIM(b.location_name);

ALTER TABLE public.smart_dealer_locations
  DROP CONSTRAINT IF EXISTS smart_dealer_locations_customer_name_unique;

ALTER TABLE public.smart_dealer_locations
  ADD CONSTRAINT smart_dealer_locations_customer_name_unique
  UNIQUE (customer_id, location_name);

CREATE INDEX IF NOT EXISTS idx_dealer_locations_customer
  ON public.smart_dealer_locations (customer_id);

COMMENT ON TABLE public.smart_dealer_locations IS
  'Configured store locations per dealer (GA4 customer_id + display name). '
  'Location Breakdown uses this when inv_location is unknown — cron can map inv_location separately.';

COMMENT ON COLUMN public.smart_dealer_locations.customer_id IS
  'GA4 client_id (smart_hoot_config.ga4_customer_id).';

COMMENT ON COLUMN public.smart_dealer_locations.location_name IS
  'Display label in Location Breakdown; matches smart_final_data.inv_location when filled.';

GRANT SELECT ON public.smart_dealer_locations TO anon, authenticated, service_role;
GRANT ALL ON public.smart_dealer_locations TO service_role;
